# Generated by Django 3.2.2 on 2022-12-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Class',
            field=models.CharField(choices=[('Computer Maths', 'Computer Maths'), ('Bio Maths', 'Bio Maths'), ('Pure Science', 'Pure Science'),('Commerce','Commerce'),('Computer Commmerce', 'Computer Commmerce')], default='Computer Maths', max_length=29),
        ),
    ]
