# Generated by Django 3.2.2 on 2024-11-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0003_auto_20240921_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Type_of_complaint',
            field=models.CharField(choices=[('ClassRoom', 'ClassRoom'), ('Teacher', 'Teacher'), ('HeadMaster', 'HeadMaster'), ('RuralSchoolManagement', 'RuralSchoolManagement'), ('Chief Educational Officer (CEO)', 'Chief Educational Officer (CEO)'), ('District Educational Officer (DEO)', 'District Educational Officer (DEO)'), ('Other Educational Officer', 'Other Educational Officer')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Branch',
            field=models.CharField(choices=[('Computer Maths', 'Computer Maths'), ('Bio Maths', 'Bio Maths'), ('Pure Science', 'Pure Science'), ('Commerce', 'Commerce'), ('Computer Commerce', 'Computer Commerce')], default='Computer Maths', max_length=29),
        ),
        migrations.AlterField(
            model_name='profile',
            name='collegename',
            field=models.CharField(choices=[('School1', 'School1'), ('School2', 'School2'), ('School3', 'School3')], max_length=29),
        ),
    ]
