# Generated by Django 3.2.2 on 2024-11-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0004_auto_20241102_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='Type_of_complaint',
            new_name='Type_of_issue',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Branch',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='collegename',
            new_name='schoolname',
        ),
    ]
