# Generated by Django 3.2.2 on 2024-11-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0005_auto_20241102_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Type_of_issue',
            field=models.CharField(choices=[('PlayGround', 'PlayGround'), ('Water Supply', 'Water Supply'), ('WashRoom', 'WashRoom'), ('Food Supply', 'Food Supply'), ('Sports & Games', 'Sports & Games'), ('Technical Equipment', 'Technical Equipment'), ('Other Issues', 'Other Issues')], max_length=200, null=True),
        ),
    ]
