# Generated by Django 3.2.2 on 2024-11-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0006_alter_complaint_type_of_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Subject',
            field=models.CharField(choices=[('Teaching Staff', 'Teaching Staff'), ('HeadMaster', 'HeadMaster'), ('District Educational Officer (DEO)', 'District Educational Officer (DEO)'), ('Chief Educational Officer (CEO)', 'Chief Educational Officer (CEO)'), ('Other Educational Officers', 'Other Educational Officers')], max_length=200, null=True),
        ),
    ]
